name: Govulncheck

permissions:
  contents: read

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          path: app

      - name: Checkout engine
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: catnet-io/engine
          path: engine
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libwebkit2gtk-4.0-dev || true
      
      - name: Mock frontend dist
        shell: bash
        working-directory: app
        run: mkdir -p frontend/dist; echo "mock" > frontend/dist/index.html
      
      - name: Run govulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1
        with:
          go-version-input: '1.26.x'
          go-package: ./...
          work-dir: ./app
          repo-checkout: false
